
GET http://localhost:5273/quotes/1
###
POST   http://localhost:5273/quotes/
Content-Type: application/json

{
    "Text":"Be yourself!",
    "Author": "Chai tae"
}
###
PUT http://localhost:5273/quotes/
Content-Type: application/json

{
    "oldText":"Be yourself",
    "newText":"Be somebodyelse!",
    "Author": "Chai tae"
}

###
PUT http://localhost:5273/quotes/
Content-Type: application/json

{
    "oldText":"Be yourself",
    "newText":"Be somebodyelse!"
}
###
DELETE http://localhost:5273/quotes/1