
GET http://localhost:5273/quote/1
###
POST   http://localhost:5273/AddQuote/
Content-Type: application/json

{
    "Text":"Be yourself!",
    "Author": "Chai tae"
}
###
PUT http://localhost:5273/UpdateQuote/
Content-Type: application/json

{
    "oldText":"Be yourself",
    "newText":"Be somebodyelse!",
    "Author": "Chai tae"
}

###
DELETE http://localhost:5273/DeleteQuote/1